//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RoomDetails.Models
{
    using System;
    using System.Collections.Generic;
    using System.Web;
    using System.ComponentModel.DataAnnotations;

    public partial class Room_Details
    {
         public int Room_Id { get; set; }
        
        public int Room_Number { get; set; }
        


        public int Room_Floor { get; set; }



        [Required(ErrorMessage = "This field is required")]
        [StringLength(100, ErrorMessage = "Minimum 3 and minimum 5 and maximum 500 characters are allowed", MinimumLength = 3)]

        public string Room_Type { get; set; }
       

        public int Room_rent { get; set; }

        public string Is_Available { get; set; }
    }
}
